### PR TITLE
Adding support for vsixgallery.com

### PR DESCRIPTION
**Pull request by madskristensen**
This change will do a few cool things;

1. Push artifacts without the full path in the link and with a nice description 
2. Upload the compiled .vsix file to vsixgallery.com

### CODE REVIEW

**Comment by aaubry** [comment]
Cool

**Comment by xt0rted** [comment]
At the moment the build number on vsixgallery.com is 1.5.1 which is the same as what's in the vs gallery. Shouldn't appveyor.yml of been updated to include this step as well?
```yaml
before_build:  
   - ps: Vsix-IncrementVsixVersion -updateBuildVersion 
```

**Comment by madskristensen** [comment]
Yes,  it should say:

```yaml
before_build:  
   - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
```

I didn't do that because you do some custom version stuff already and so I wasn't sure if this would break things.

**Comment by aaubry** [comment]
The version number comes from the GIT repository. I do it that way because I want to tie each release to a specific commit. I should probably create a **release** branch, as in https://github.com/aaubry/YamlDotNet, and publish to vsixgallery.com only on that branch.
What should be added to:
```yaml
after_test:
  # Push artifacts and publish the nighly build to http://vsixgallery.com
  - ps: Vsix-PushArtifacts .\YamlDotNetEditor\bin\*\*.vsix | Vsix-PublishToGallery
```
in order to restrict the command to the release branch?

**Comment by madskristensen** [comment]
vsixgallery.com is not an official VS extension gallery. The purpose of the site is to provide a way for users to subscribe to nightly builds of their favorite extensions. See this http://vsixgallery.com/guide/feed/ 

I would suggest you always increment the build number in the .vsixmanifest just like Visual Studio itself or Windows for that matter always do. Visual Studio 2015 CTP 5 is version 14.0.22512.0. The build number (22512) always goes up with all their releases. The important part is the major and minor version (14 and 0 respectively).

So when you are ready to make a new release of your extension, just manually set the version to 1.6 in the .vsixmanifest and your extension will become 1.6.100 (where 100 is the current build number from AppVeyor). 

That's what I do in all my extensions. 

That also eliminates the need for having extensions with version 1.5.1 like you do. It's always just [major].[minor].[build number]

**Comment by aaubry** [comment]
I need to think a bit more about the versioning. For now, I have updated the build script so that the nightly builds use the AppVeyor build number.

**Pull request merged**
